nome=input('Digite um nome')
mais = nome.upper()
print(mais)
# menos = nome.lower()
print(nome.lower())
n = nome.count(' ', 0, len(nome))
print(len(nome) - n)
prim = nome.split(' ')
print(len(prim[0]))